name: 'Chromatic'

on:
  pull_request:
    branches:
      - main

jobs:
  Chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Check for changes in components folder
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q '^src/components/.*\.tsx$'; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        if: steps.check_changes.outputs.changes == 'true'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}