name: 'Chromatic'

on:
  merge_group:
    types: [checks_requested]
    branches: [main]
  workflow_dispatch:

jobs:
  Chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true

      - name: Update PR status
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          OWNER: ksavinN
          REPO: Test-Chromium
          SHA: ${{ github.sha }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$OWNER/$REPO/statuses/$SHA \
            -d '{
              "state": "success",
              "target_url": "https://github.com/$OWNER/$REPO/actions/runs/${{ github.run_id }}",
              "description": "Chromatic deployment succeeded",
              "context": "Chromatic"
            }'

      - name: Mark as success
        run: exit 0
