

name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a sample script
        run: echo "Manual Trigger executed!"
      - name: Mark as success
        run: exit 0