

name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a sample script
        run: echo "Manual Trigger executed!"

      - name: Mark as success
        run: exit 1

      - name: Update PR status
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          OWNER: KsavinN
          REPO: Test-Chromium
          SHA: ${{ github.sha }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$OWNER/$REPO/statuses/$SHA \
            -d '{
              "state": "success",
              "target_url": "https://github.com/$OWNER/$REPO/actions/runs/${{ github.run_id }}",
              "description": "Manual Trigger executed successfully",
              "context": "Manual Trigger"
            }'


